
CREATE TABLE Cars(
Id INT PRIMARY KEY NOT NULL,
Model varchar(25),
SeatsNumber INT
)

CREATE SEQUENCE seq_CarId
AS INT
START WITH 1
INCREMENT BY 1

SELECT NEXT VALUE FOR seq_CarId

INSERT INTO Cars(Id, Model, SeatsNumber)
VALUES
(NEXT VALUE FOR seq_CarId, 'Megane',5),
(NEXT VALUE FOR seq_CarId, '307',3),
(NEXT VALUE FOR seq_CarId, 'Astra',3)
