
CREATE TABLE Example
(
	Id INT PRIMARY KEY IDENTITY,
	Name varchar(50) NOT NULL
)

INSERT INTO Example
VALUES('Nasko');

SELECT * FROM Example

SET IDENTITY_INSERT Example ON
	INSERT INTO Example (Id, Name)
	VALUES (4, 'Asi')
SET IDENTITY_INSERT Example OFF; 

SELECT * FROM Example
